version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: paxful
      POSTGRES_PASSWORD: paxful
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
  node:
    build: ./client/
    container_name: node
    environment:
      - NODE_ENV=development
    stdin_open: true
    volumes:
      - "./client/src:/app/src"
      - "./client/public:/app/public"
    ports:
      - "3000:3000"
  django:
    build: ./server/
    container_name: django
    entrypoint: "/usr/bin/wait-for-it.sh postgres:5432 -t 60 --"
    command: "python /app/run.py runserver 0.0.0.0:8000"
    volumes:
      - "./server:/app"
    environment:
      - PYTHONUNBUFFERED=0
      - DATABASE_URL=postgres://paxful:paxful@postgres:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - node
